version: '3.0'

services:
  # FastAPI service configuration
  web:
    build: fastapi                # Build from ./fastapi/Dockerfile
    ports:
      - 8000:8000                # Map host port 8000 to container port 8000
    volumes:
      - ./fastapi:/app           # Mount local fastapi directory to /app in container
    networks:
      - ollama-network           # Connect to the ollama network
    depends_on:
      - ollama

  # Ollama service configuration
  ollama:
    build: ollama                # Build from ./ollama/Dockerfile
    ports:
      - 11434:11434             # Map host port 11434 to container port 11434 (Ollama API)
    volumes:
      - ollama-vol:/ollama      # Mount named volume for persistent Ollama data
    networks:
      - ollama-network          # Connect to the ollama network
    entrypoint: ["/usr/bin/bash", "/pull-llama.sh"]  # Run pull-llama.sh on startup

# Define named volumes for persistent data
volumes:
  ollama-vol:                    # Named volume for Ollama data
    driver: local               # Use local driver for volume

# Define networks for service communication
networks:
  ollama-network:               # Network for FastAPI and Ollama communication
    driver: bridge             # Use bridge network driver
