version: "3"

services:
  web:
    build: fastapi
    ports:
      - 8000:8000
    volumes:
      - ./fastapi:/app
      - ./opensearch:/app/opensearch
      - ./data:/app/data
    environment:                                  # Add this section
      - OPENSEARCH_URL=http://opensearch:9200    # OpenSearch connection URL
      - OLLAMA_URL=http://ollama:11434   
    networks:
      - llama-net
    depends_on:
      - opensearch
      - ollama
    entrypoint: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  ollama:
    build: ollama
    ports:
      - 11434:11434
    volumes:
      - llama-vol:/ollama
    networks:
      - llama-net
    entrypoint: ["/usr/bin/bash", "/pull-llama.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/api/version && curl -sf http://localhost:11434/api/tags | grep -q 'gemma2:2b'"]
      interval: 30s
      timeout: 10s
      retries: 3

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - llama-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    networks:
      - llama-net
    depends_on:
      - opensearch

networks:
  llama-net:
    driver: bridge

volumes:
  llama-vol:
    driver: local
  opensearch-data:
    driver: local
