version: '3.8'  # Updated to a more recent version for better features

services:
  # FastAPI service configuration
  web:
    build:
      context: .  # Set build context to project root
      dockerfile: fastapi/Dockerfile  # Specify Dockerfile path
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    volumes:
      - ./fastapi:/app/fastapi  # Mount local fastapi directory to /app/fastapi in container
      - ./opensearch:/app/opensearch  # Mount local opensearch directory to /app/opensearch in container
      - ./pdfs:/app/pdfs  # Mount local pdfs directory to /app/pdfs in container
    networks:
      - ollama-network  # Connect to the ollama network
    depends_on:
      opensearch:
        condition: service_healthy  # Wait for OpenSearch to be healthy
      ollama:
        condition: service_started  # Wait for Ollama to start
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
      - OLLAMA_URL=http://ollama:11434

  # Ollama service configuration
  ollama:
    build: ollama  # Build from ./ollama/Dockerfile
    ports:
      - "11434:11434"  # Map host port 11434 to container port 11434 (Ollama API)
    volumes:
      - ollama-vol:/ollama  # Named volume for persistent Ollama data
    networks:
      - ollama-network  # Connect to the ollama network
    entrypoint: ["/usr/bin/bash", "/pull-llama.sh"]  # Run pull-llama.sh on startup

  # OpenSearch service configuration
  opensearch:
    image: opensearchproject/opensearch:2.9.0  # Use official OpenSearch image
    container_name: opensearch
    environment:
      - discovery.type=single-node  # Single-node cluster
      - DISABLE_SECURITY_PLUGIN=true  # Disable security for development
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m  # Set JVM heap size
    volumes:
      - opensearch-data:/usr/share/opensearch/data  # Named volume for OpenSearch data
    ports:
      - "9200:9200"  # OpenSearch HTTP API
      - "9600:9600"  # Performance Analyzer
    networks:
      - ollama-network  # Connect to the ollama network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

# Define named volumes for persistent data
volumes:
  ollama-vol:
    driver: local
  opensearch-data:
    driver: local

# Define networks for service communication
networks:
  ollama-network:
    driver: bridge
